# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FirstUI(object):
    def setupUi(self, FirstUI):
        FirstUI.setObjectName("FirstUI")
        FirstUI.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(FirstUI)
        self.pushButton.setGeometry(QtCore.QRect(230, 190, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.helloButton = QtWidgets.QPushButton(FirstUI)
        self.helloButton.setGeometry(QtCore.QRect(50, 190, 111, 41))
        self.helloButton.setObjectName("helloButton")

        self.retranslateUi(FirstUI)
        QtCore.QMetaObject.connectSlotsByName(FirstUI)

    def retranslateUi(self, FirstUI):
        _translate = QtCore.QCoreApplication.translate
        FirstUI.setWindowTitle(_translate("FirstUI", "Dialog"))
        self.pushButton.setText(_translate("FirstUI", "open new ui"))
        self.helloButton.setText(_translate("FirstUI", "hello"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FirstUI = QtWidgets.QDialog()
    ui = Ui_FirstUI()
    ui.setupUi(FirstUI)
    FirstUI.show()
    sys.exit(app.exec_())
